# /avalon/docker-compose.yaml
services:
  avalon-app:
    build:
      context: .
      dockerfile: docker-avalon-app.dev.dockerfile
    container_name: avalon-app
    hostname: avalon-app
    ports:
      - "5000:5000"
      - "5173:5173"
      - "5174:5174"
    volumes:
      - .:/app:delegated
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
